# Generated by Django 5.2.1 on 2025-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('full_tiffin_description', models.TextField()),
                ('full_tiffin_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('half_tiffin_type1_description', models.TextField()),
                ('half_tiffin_type1_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('half_tiffin_type2_description', models.TextField()),
                ('half_tiffin_type2_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
